# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: jaeger-hello

logging:
  level: info

provider:
  formatter: http://formatter:8080
  publisher: http://publisher:8080

